services:
  wiki-db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - wiki-db-data:/var/lib/mysql
  adminer:
    image: adminer
    depends_on:
      - wiki-db
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  wiki-db-data: