name: Build & Deploy to Scaleway

on:
  push:
    branches: [ "bunny-deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: cd jobs/process-dump
    
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ vars.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}

    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3    
    - name: Build the Docker image
      run: docker build . -t ${{ vars.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}/my-docker-image
    
    - name: Push the Docker Image
      run: docker push ${{ vars.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}/my-docker-image
