name: Lint App

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      
      - name: "Install Dependencies"
        run: "pnpm --dir app install"

      - name: Run lint
        run: "pnpm --dir app run lint"
      